### ISSUE TITLE
Where can I register OPENAI_API_KEY?

### ISSUE THREAD

**Issue by soiqualang** [elhadjx/meowbot#2]
Sorry for the silly question, is the OPENAI_API_KEY you signed up for for a fee? Where did you register, is it the categories below?
I see OpenAI has many kinds of Language models, which one are you using?

https://openai.com/api/pricing/

![image](https://user-images.githubusercontent.com/2648020/216864936-472abed5-e228-455a-b89d-53fd8fcacd07.png)

**Comment by elhadjx** [comment]
Go to [https://platform.openai.com/account/api-keys](https://platform.openai.com/account/api-keys)
Create New Secret Key, Copy it when it appears because you wont be able to see it again. if something goes wrong you can create another one but it'll use the same balance from the account.
to check for the account balance, Go to [https://platform.openai.com/account/usage](https://platform.openai.com/account/usage)
